{% set name = "django-ses" %}
{% set version = "3.2.0" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: 6c9e56b610317ed16701951870e6b498d04bbc4aba46d957917585580803d182

build:
  noarch: python
  number: 0
  script: {{ PYTHON }} -m pip install . -vv

requirements:
  build:
    - poetry
  host:
    - python >=3.6
    - pip
    - poetry
  run:
    - poetry
    - python >=3.7
    - django >=2.2
    - boto3 >=1.0.0
    - pytz >=2016.10
    - importlib-metadata
    - cryptography
    - requests

test:
  commands:
    - python -c "import importlib.util; assert importlib.util.find_spec('django_ses')"

about:
  home: https://github.com/django-ses/django-ses
  license: MIT
  license_family: MIT
  license_file: LICENSE
  summary: A Django email backend for Amazon's Simple Email Service

extra:
  recipe-maintainers:
    - MichelML
